version: '3.8'

volumes:
  milu-assistant-web-data:
    name: milu-assistant-web-data
  milu-assistant-web-secrets:
    name: milu-assistant-web-secrets

services:
  milu-assistant-web:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    image: milu-assistant-web:latest
    container_name: milu-assistant-web
    restart: always
    ports:
      - "127.0.0.1:8088:8088"
    # environment:
    #   - MILU_AUTH_ENABLED=true
    #   - MILU_AUTH_USERNAME=admin
    #   - MILU_AUTH_PASSWORD=yourpassword
    volumes:
      - milu-assistant-web-data:/app/working
      - milu-assistant-web-secrets:/app/working.secret
